
-- 1. Criar Tabela de Perfis (se não existir)
CREATE TABLE IF NOT EXISTS public.profiles (
    id TEXT PRIMARY KEY, 
    name TEXT NOT NULL,
    wins INTEGER DEFAULT 0,
    matches INTEGER DEFAULT 0,
    total_score INTEGER DEFAULT 0
);

-- 2. Garantir que as colunas necessárias existam (caso a tabela já existisse antes)
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='avatar_url') THEN
        ALTER TABLE public.profiles ADD COLUMN avatar_url TEXT DEFAULT 'https://api.dicebear.com/7.x/avataaars/svg?seed=FreeFire';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='last_seen') THEN
        ALTER TABLE public.profiles ADD COLUMN last_seen TIMESTAMP WITH TIME ZONE DEFAULT NOW();
    END IF;
END $$;

-- 3. Criar Tabela de Amizades
CREATE TABLE IF NOT EXISTS public.friendships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    friend_id TEXT REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, friend_id)
);

-- 4. Habilitar RLS (Segurança)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.friendships ENABLE ROW LEVEL SECURITY;

-- 5. Criar Políticas de Acesso
DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Acesso público perfis" ON public.profiles;
    DROP POLICY IF EXISTS "Acesso público amizades" ON public.friendships;
END $$;

CREATE POLICY "Acesso público perfis" ON public.profiles FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acesso público amizades" ON public.friendships FOR ALL USING (true) WITH CHECK (true);

-- 6. Habilitar Realtime
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
        IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime' AND puballtables = true) THEN
            BEGIN
                ALTER PUBLICATION supabase_realtime ADD TABLE public.profiles;
            EXCEPTION WHEN OTHERS THEN RAISE NOTICE 'profiles já na publicação';
            END;
            BEGIN
                ALTER PUBLICATION supabase_realtime ADD TABLE public.friendships;
            EXCEPTION WHEN OTHERS THEN RAISE NOTICE 'friendships já na publicação';
            END;
        END IF;
    END IF;
END $$;
